### ISSUE TITLE
Suggestion: Update to 1.20.1

### ISSUE THREAD

**Issue by VillainVibe** [StormDragon-64/Placement-Plus#2]
Hi there, 

I was wondering if you have any plans of updating to 1.20.1 ? 
Cheers

**Comment by Sshmoob** [comment]
Just use [Sinytra Connector](https://modrinth.com/mod/connector) to use the [fabric version of accurate block placement](https://modrinth.com/mod/accurate-block-placement-reborn) on forge, which I’m pretty sure is already toggleable.

**Comment by VillainVibe** [comment]
I'm not a fan of mix loaders together.
But thanks for the suggestion.
